spring:
   application:
      name: eurekaserver

eureka:
   instance:
      enabled: true
      statusPageUrl: https://${eureka.hostname}/info
      healthCheckUrl: https://${eureka.hostname}/health
      homePageUrl: https://${eureka.hostname}/
   client:
      registerWithEureka: false
      fetchRegistry: false
server:
   port: 8761