server:
    port: 8083
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: demo
          uri: lb://DEMO
          predicates:
            - Path=/hello/**
eureka:
    client:
        service-url:
            defaultZone: http://eurekaserver:8761/eureka
        fetch-registry: true
        register-with-eureka: true