server:
    port: 8083
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: demo
          uri: lb://DemoMicroservice  # Matches the name in demo's application.yml
          predicates:
            - Path=/hello/**
eureka:
    client:
        service-url:
            defaultZone: http://eureka:8761/eureka  # Updated service name
        fetch-registry: true
        register-with-eureka: true